jwt:
   secret: ${JWT_SECRET}
   expiration-token: 3600000
   tokenRefreshTimeExpiration: 86400000

spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/postgres
     username: postgres
     password:
  jpa:
     hibernate:
       ddl-auto: none
     show-sql: true
     properties:
        hibernate:
           format_sql: true
           dialect:  org.hibernate.dialect.PostgreSQL94Dialect